# Generated by Django 4.2.7 on 2026-01-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_donated', models.DateField()),
                ('units_donated', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donation History',
                'verbose_name_plural': 'Donation Histories',
                'ordering': ['-date_donated'],
            },
        ),
        migrations.RemoveField(
            model_name='donorhistory',
            name='donor',
        ),
        migrations.AlterModelOptions(
            name='donorprofile',
            options={'verbose_name': 'Donor Profile', 'verbose_name_plural': 'Donor Profiles'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='last_donated',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='O+', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='donation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
