# Generated by Django 4.2.7 on 2026-01-22 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_bloodrequest_donornotification_donorresponse_and_more'),
        ('donors', '0002_donationhistory_remove_donorhistory_donor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='blood_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.bloodrequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Available to donate'),
        ),
        migrations.DeleteModel(
            name='DonorHistory',
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='blood_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.bloodrequest'),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_history', to='donors.donorprofile'),
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospitalprofile'),
        ),
    ]
