# Generated by Django 6.0.1 on 2026-01-30 05:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_alter_donorprofile_is_available_and_more'),
        ('hospitals', '0004_delete_donornotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donornotification',
            options={'ordering': ['priority_order', '-sent_at']},
        ),
        migrations.AlterModelOptions(
            name='donorprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Donor Profile', 'verbose_name_plural': 'Donor Profiles'},
        ),
        migrations.AddField(
            model_name='donornotification',
            name='is_notified',
            field=models.BooleanField(default=False, help_text='Has this donor been notified?'),
        ),
        migrations.AddField(
            model_name='donornotification',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='When donor was notified', null=True),
        ),
        migrations.AddField(
            model_name='donornotification',
            name='priority_order',
            field=models.IntegerField(default=0, help_text='Order to notify (1, 2, 3...)'),
        ),
        migrations.AddField(
            model_name='donornotification',
            name='responded_at',
            field=models.DateTimeField(blank=True, help_text='When donor responded', null=True),
        ),
        migrations.AddField(
            model_name='donornotification',
            name='response_notes',
            field=models.TextField(blank=True, help_text="Donor's response notes/reason"),
        ),
        migrations.AddField(
            model_name='donornotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationhistory',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.hospitalprofile'),
        ),
        migrations.AlterField(
            model_name='donationhistory',
            name='units_donated',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='donornotification',
            name='blood_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_notifications', to='hospitals.bloodrequest'),
        ),
        migrations.AlterField(
            model_name='donornotification',
            name='distance',
            field=models.FloatField(blank=True, help_text='Distance in kilometers', null=True),
        ),
        migrations.AlterField(
            model_name='donornotification',
            name='match_score',
            field=models.FloatField(blank=True, help_text='Match score between 0 and 1', null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)]),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=4),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='donation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='donornotification',
            index=models.Index(fields=['blood_request', 'status'], name='donors_dono_blood_r_3bde97_idx'),
        ),
        migrations.AddIndex(
            model_name='donornotification',
            index=models.Index(fields=['donor', '-sent_at'], name='donors_dono_donor_i_491940_idx'),
        ),
        migrations.AddIndex(
            model_name='donornotification',
            index=models.Index(fields=['blood_request', 'priority_order'], name='donors_dono_blood_r_5c225a_idx'),
        ),
    ]
