# Generated by Django 6.0.1 on 2026-02-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_alter_donornotification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donornotification',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donornotification',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donornotification',
            name='match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donornotification',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donornotification',
            name='priority_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donornotification',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donornotification',
            name='response_notes',
            field=models.TextField(blank=True),
        ),
    ]
