# Generated by Django 6.0.1 on 2026-03-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_donorprofile_points_alter_donornotification_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donornotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20),
        ),
    ]
