# Generated by Django 6.0.1 on 2026-03-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0007_alter_donornotification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donornotification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('accepted', 'Accepted'), ('donor_confirmed', 'Donor Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled'), ('mismatch', 'Mismatch')], default='pending', max_length=20),
        ),
    ]
