# Generated by Django 6.0.1 on 2026-02-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_customuser_failed_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('donor', 'Donor'), ('hospital', 'Hospital'), ('super_admin', 'Super Admin')], default='donor', max_length=15),
        ),
    ]
