# Generated by Django 6.0.1 on 2026-01-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_bloodrequest_donornotification_donorresponse_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonorResponse',
        ),
    ]
