# Generated by Django 6.0.1 on 2026-01-30 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_delete_donorresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonorNotification',
        ),
    ]
