# Generated by Django 6.0.1 on 2026-03-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_alter_bloodrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='condition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('donor_confirmed', 'Donor Confirmed'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('mismatch', 'Mismatch')], default='pending', max_length=20),
        ),
    ]
